In [1]:
import torch

In [2]:
# Create an array with empty, values already present in that memory slot will be added
x = torch.empty(5, 3)
# Create a random array
x = torch.rand(5, 3)
# Create an array with zeros
x = torch.zeros(5, 3, dtype=torch.long)
# Create an array with values
x = torch.tensor([5.5, 3])
# Use an existing array and setup new values in it
x = x.new_ones(5, 3, dtype=torch.double)
# Override the dtypes
x = torch.randn_like(x, dtype=torch.float)
# Get size of tensor
print x.size()

In [7]:
# Operations can be done in two ways
y = torch.rand(5,3)
print torch.add(x,y)
# You can add in place using the post-fix _ after an operator
y.add_(x)
# the out argument assigns the result of add to the result variable
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print x + y
# use the view function to resize a tensor
x = torch.randn(4, 4)
x.view(16)

tensor([[0.1389, 0.1903, 0.1224],
        [0.1639, 0.4152, 0.7548],
        [0.1406, 0.3086, 0.0117],
        [0.7677, 0.1163, 0.3584],
        [0.1861, 0.4324, 0.7825]])
tensor([[0.1389, 0.1903, 0.1224],
        [0.1639, 0.4152, 0.7548],
        [0.1406, 0.3086, 0.0117],
        [0.7677, 0.1163, 0.3584],
        [0.1861, 0.4324, 0.7825]])


tensor([ 0.8386,  1.1626,  0.2314,  1.0849, -0.2165, -0.7072,  1.6830, -1.8756,
        -0.6201, -0.9406, -1.0786,  0.3770,  2.1150, -0.0485,  2.2614, -0.2265])

In [8]:
import torchvision.transforms as transforms

The tutorial for using CNN via pytorch
https://algorithmia.com/blog/convolutional-neural-nets-in-pytorch

In [10]:
from torch.utils.data.sampler import SubsetRandomSampler

In [11]:
SubsetRandomSampler?

In [12]:
import numpy as np

In [14]:
np.arange(5000, dtype=np.int64)

array([   0,    1,    2, ..., 4997, 4998, 4999])

In [15]:
import torch.nn

In [16]:
torch.nn.Conv2d?